using System.Text.Json.Serialization;

namespace Tavstal.WynnNetSDK.Models.Items.Enums;

public enum EEmblem
{
    [JsonPropertyName("diamond6")]
    DIAMOND6,
    [JsonPropertyName("diamond_6")]
    DIAMOND_6,
    [JsonPropertyName("diamond5")]
    DIAMOND5,
    [JsonPropertyName("diamond_5")]
    DIAMOND_5,
    [JsonPropertyName("diamond4")]
    DIAMOND4,
    [JsonPropertyName("diamond_4")]
    DIAMOND_4,
    [JsonPropertyName("diamond3")]
    DIAMOND3,
    [JsonPropertyName("diammond_3")]
    DIAMMOND_3,
    [JsonPropertyName("diamond2")]
    DIAMOND2,
    [JsonPropertyName("diamond_2")]
    DIAMOND_2,
    [JsonPropertyName("diamond1")]
    DIAMOND1,
    [JsonPropertyName("diamond_1")]
    DIAMOND_1,
    [JsonPropertyName("shield6")]
    SHIELD6,
    [JsonPropertyName("shield_6")]
    SHIELD_6,
    [JsonPropertyName("shield5")]
    SHIELD5,
    [JsonPropertyName("shield_5")]
    SHIELD_5,
    [JsonPropertyName("shield4")]
    SHIELD4,
    [JsonPropertyName("shield_4")]
    SHIELD_4,
    [JsonPropertyName("shield3")]
    SHIELD3,
    [JsonPropertyName("shield_3")]
    SHIELD_3,
    [JsonPropertyName("shield2")]
    SHIELD2,
    [JsonPropertyName("shield_2")]
    SHIELD_2,
    [JsonPropertyName("shield1")]
    SHIELD1,
    [JsonPropertyName("shield_1")]
    SHIELD_1,
    [JsonPropertyName("sticker6")]
    STICKER6,
    [JsonPropertyName("sticker_6")]
    STICKER_6,
    [JsonPropertyName("sticker5")]
    STICKER5,
    [JsonPropertyName("sticker_5")]
    STICKER_5,
    [JsonPropertyName("sticker4")]
    STICKER4,
    [JsonPropertyName("sticker_4")]
    STICKER_4,
    [JsonPropertyName("sticker3")]
    STICKER3,
    [JsonPropertyName("sticker_3")]
    STICKER_3,
    [JsonPropertyName("sticker2")]
    STICKER2,
    [JsonPropertyName("sticker_2")]
    STICKER_2,
    [JsonPropertyName("sticker1")]
    STICKER1,
    [JsonPropertyName("sticker_1")]
    STICKER_1,
    [JsonPropertyName("square6")]
    SQUARE6,
    [JsonPropertyName("square_6")]
    SQUARE_6,
    [JsonPropertyName("square5")]
    SQUARE5,
    [JsonPropertyName("square_5")]
    SQUARE_5,
    [JsonPropertyName("square4")]
    SQUARE4,
    [JsonPropertyName("square_4")]
    SQUARE_4,
    [JsonPropertyName("square3")]
    SQUARE3,
    [JsonPropertyName("square_3")]
    SQUARE_3,
    [JsonPropertyName("square2")]
    SQUARE2,
    [JsonPropertyName("square_2")]
    SQUARE_2,
    [JsonPropertyName("square")]
    SQUARE
}
