using System.Text.Json.Serialization;

namespace Tavstal.WynnNetSDK.Models.Items.Enums;

public enum EIdentification
{
    [JsonPropertyName("baseDamage")]
    BASE_DAMAGE,
    [JsonPropertyName("baseEarthDamage")]
    BASE_EARTH_DAMAGE,
    [JsonPropertyName("baseThunderDamage")]
    BASE_THUNDER_DAMAGE,
    [JsonPropertyName("baseWaterDamage")]
    BASE_WATER_DAMAGE,
    [JsonPropertyName("baseFireDamage")]
    BASE_FIRE_DAMAGE,
    [JsonPropertyName("baseAirDamage")]
    BASE_AIR_DAMAGE,
    [JsonPropertyName("strength")]
    STRENGTH,
    [JsonPropertyName("dexterity")]
    DEXTERITY,
    [JsonPropertyName("intelligence")]
    INTELLIGENCE,
    [JsonPropertyName("defence")]
    DEFENCE,
    [JsonPropertyName("agility")]
    AGILITY,
    [JsonPropertyName("healthRegenRaw")]
    HEALTH_REGEN_RAW,
    [JsonPropertyName("rawSpellDamage")]
    RAW_SPELL_DAMAGE,
    [JsonPropertyName("rawMainAttackDamage")]
    RAW_MAIN_ATTACK_DAMAGE,
    [JsonPropertyName("elementalDefence")]
    ELEMENTAL_DEFENCE,
    [JsonPropertyName("rawDefence")]
    RAW_DEFENCE,
    [JsonPropertyName("walkSpeed")]
    WALK_SPEED,
    [JsonPropertyName("airDamage")]
    AIR_DAMAGE,
    [JsonPropertyName("thunderDamage")]
    THUNDER_DAMAGE,
    [JsonPropertyName("spellDamage")]
    SPELL_DAMAGE,
    [JsonPropertyName("raw1stSpellCost")]
    RAW_1ST_SPELL_COST,
    [JsonPropertyName("knockback")]
    KNOCKBACK,
    [JsonPropertyName("fireDamage")]
    FIRE_DAMAGE,
    [JsonPropertyName("mainAttackDamage")]
    MAIN_ATTACK_DAMAGE,
    [JsonPropertyName("lifeSteal")]
    LIFE_STEAL,
    [JsonPropertyName("manaSteal")]
    MANA_STEAL,
    [JsonPropertyName("weakenEnemy")]
    WEAKEN_ENEMY,
    [JsonPropertyName("waterDefence")]
    WATER_DEFENCE,
    [JsonPropertyName("airDefence")]
    AIR_DEFENCE,
    [JsonPropertyName("rawDexterity")]
    RAW_DEXTERITY,
    [JsonPropertyName("manaRegen")]
    MANA_REGEN,
    [JsonPropertyName("combatExperience")]
    COMBAT_EXPERIENCE,
    [JsonPropertyName("slowEnemy")]
    SLOW_ENEMY,
    [JsonPropertyName("waterDamage")]
    WATER_DAMAGE,
    [JsonPropertyName("earthDefence")]
    EARTH_DEFENCE,
    [JsonPropertyName("exploding")]
    EXPLODING,
    [JsonPropertyName("thunderDefence")]
    THUNDER_DEFENCE,
    [JsonPropertyName("rawAgility")]
    RAW_AGILITY,
    [JsonPropertyName("reflection")]
    REFLECTION,
    [JsonPropertyName("earthDamage")]
    EARTH_DAMAGE,
    [JsonPropertyName("healthRegen")]
    HEALTH_REGEN,
    [JsonPropertyName("rawHealth")]
    RAW_HEALTH,
    [JsonPropertyName("damage")]
    DAMAGE,
    [JsonPropertyName("elementalDamage")]
    ELEMENTAL_DAMAGE,
    [JsonPropertyName("rawAttackSpeed")]
    RAW_ATTACK_SPEED,
    [JsonPropertyName("sprint")]
    SPRINT,
    [JsonPropertyName("raw4thSpellCost")]
    RAW_4TH_SPELL_COST,
    [JsonPropertyName("rawIntelligence")]
    RAW_INTELLIGENCE,
    [JsonPropertyName("rawAirDamage")]
    RAW_AIR_DAMAGE,
    [JsonPropertyName("jumpHeight")]
    JUMP_HEIGHT,
    [JsonPropertyName("rawStrength")]
    RAW_STRENGTH,
    [JsonPropertyName("rawElementalSpellDamage")]
    RAW_ELEMENTAL_SPELL_DAMAGE,
    [JsonPropertyName("thorns")]
    THORNS,
    [JsonPropertyName("fireDefence")]
    FIRE_DEFENCE,
    [JsonPropertyName("raw3rdSpellCost")]
    RAW_3RD_SPELL_COST,
    [JsonPropertyName("sprintRegen")]
    SPRINT_REGEN,
    [JsonPropertyName("poison")]
    POISON,
    [JsonPropertyName("elementalSpellDamage")]
    ELEMENTAL_SPELL_DAMAGE,
    [JsonPropertyName("rawThunderMainAttackDamage")]
    RAW_THUNDER_MAIN_ATTACK_DAMAGE,
    [JsonPropertyName("rawEarthMainAttackDamage")]
    RAW_EARTH_MAIN_ATTACK_DAMAGE,
    [JsonPropertyName("fireSpellDamage")]
    FIRE_SPELL_DAMAGE,
    [JsonPropertyName("stealing")]
    STEALING,
    [JsonPropertyName("rawThunderDamage")]
    RAW_THUNDER_DAMAGE,
    [JsonPropertyName("mainAttackRange")]
    MAIN_ATTACK_RANGE,
    [JsonPropertyName("raw2ndSpellCost")]
    RAW_2ND_SPELL_COST,
    [JsonPropertyName("1stSpellCost")]
    FIRST_SPELL_COST,
    [JsonPropertyName("ThirdSpellCost")]
    THIRD_SPELL_COST,
    [JsonPropertyName("rawFireDamage")]
    RAW_FIRE_DAMAGE,
    [JsonPropertyName("lootBonus")]
    LOOT_BONUS,
    [JsonPropertyName("fireMainAttackDamage")]
    FIRE_MAIN_ATTACK_DAMAGE,
    [JsonPropertyName("rawAirMainAttackDamage")]
    RAW_AIR_MAIN_ATTACK_DAMAGE,
    [JsonPropertyName("rawDamage")]
    RAW_DAMAGE,
    [JsonPropertyName("FourthSpellCost")]
    FOURTH_SPELL_COST,
    [JsonPropertyName("rawElementalDamage")]
    RAW_ELEMENTAL_DAMAGE,
    [JsonPropertyName("elementalMainAttackDamage")]
    ELEMENTAL_MAIN_ATTACK_DAMAGE,
    [JsonPropertyName("earthMainAttackDamage")]
    EARTH_MAIN_ATTACK_DAMAGE,
    [JsonPropertyName("thunderMainAttackDamage")]
    THUNDER_MAIN_ATTACK_DAMAGE,
    [JsonPropertyName("rawMaxMana")]
    RAW_MAX_MANA,
    [JsonPropertyName("rawAirSpellDamage")]
    RAW_AIR_SPELL_DAMAGE,
    [JsonPropertyName("SecondSpellCost")]
    SECOND_SPELL_COST,
    [JsonPropertyName("rawEarthDamage")]
    RAW_EARTH_DAMAGE,
    [JsonPropertyName("earthSpellDamage")]
    EARTH_SPELL_DAMAGE,
    [JsonPropertyName("waterSpellDamage")]
    WATER_SPELL_DAMAGE,
    [JsonPropertyName("rawFireSpellDamage")]
    RAW_FIRE_SPELL_DAMAGE,
    [JsonPropertyName("criticalDamageBonus")]
    CRITICAL_DAMAGE_BONUS,
    [JsonPropertyName("airSpellDamage")]
    AIR_SPELL_DAMAGE,
    [JsonPropertyName("rawThunderSpellDamage")]
    RAW_THUNDER_SPELL_DAMAGE,
    [JsonPropertyName("rawWaterSpellDamage")]
    RAW_WATER_SPELL_DAMAGE,
    [JsonPropertyName("rawFireMainAttackDamage")]
    RAW_FIRE_MAIN_ATTACK_DAMAGE,
    [JsonPropertyName("neutralSpellDamage")]
    NEUTRAL_SPELL_DAMAGE,
    [JsonPropertyName("neutralDamage")]
    NEUTRAL_DAMAGE,
    [JsonPropertyName("rawNeutralMainAttackDamage")]
    RAW_NEUTRAL_MAIN_ATTACK_DAMAGE,
    [JsonPropertyName("thunderSpellDamage")]
    THUNDER_SPELL_DAMAGE,
    [JsonPropertyName("rawEarthSpellDamage")]
    RAW_EARTH_SPELL_DAMAGE,
    [JsonPropertyName("rawNeutralDamage")]
    RAW_NEUTRAL_DAMAGE,
    [JsonPropertyName("rawWaterDamage")]
    RAW_WATER_DAMAGE,
    [JsonPropertyName("healingEfficiency")]
    HEALING_EFFICIENCY,
    [JsonPropertyName("rawElementalMainAttackDamage")]
    RAW_ELEMENTAL_MAIN_ATTACK_DAMAGE,
    [JsonPropertyName("airMainAttackDamage")]
    AIR_MAIN_ATTACK_DAMAGE,
    [JsonPropertyName("rawNeutralSpellDamage")]
    RAW_NEUTRAL_SPELL_DAMAGE,
    [JsonPropertyName("baseHealth")]
    BASE_HEALTH,
    [JsonPropertyName("baseEarthDefence")]
    BASE_EARTH_DEFENCE,
    [JsonPropertyName("baseFireDefence")]
    BASE_FIRE_DEFENCE,
    [JsonPropertyName("baseThunderDefence")]
    BASE_THUNDER_DEFENCE,
    [JsonPropertyName("baseWaterDefence")]
    BASE_WATER_DEFENCE,
    [JsonPropertyName("baseAirDefence")]
    BASE_AIR_DEFENCE,
    [JsonPropertyName("neutralMainAttackDamage")]
    NEUTRAL_MAIN_ATTACK_DAMAGE,
    [JsonPropertyName("leveledXpBonus")]
    LEVELED_XP_BONUS,
    [JsonPropertyName("damageFromMobs")]
    DAMAGE_FROM_MOBS,
    [JsonPropertyName("leveledLootBonus")]
    LEVELED_LOOT_BONUS,
    [JsonPropertyName("gatheringExperience")]
    GATHERING_EXPERIENCE,
    [JsonPropertyName("gatherXpBonus")]
    GATHER_XP_BONUS,
    [JsonPropertyName("gatherSpeed")]
    GATHER_SPEED,
    [JsonPropertyName("lootQuality")]
    LOOT_QUALITY,
    [JsonPropertyName("rawWaterMainAttackDamage")]
    RAW_WATER_MAIN_ATTACK_DAMAGE,
    AGILITYBONUS,
    STRENGTHBONUS
}
