using System.Text.Json.Serialization;

namespace Tavstal.WynnNetSDK.Models.Items.Enums;

public enum EItemSet
{
    [JsonPropertyName("boundless")]
    BOUNDLESS,
    [JsonPropertyName("corrupted")]
    CORRUPTED,
    [JsonPropertyName("firemoss")]
    FIREMOSS,
    [JsonPropertyName("bony")]
    BONY,
    [JsonPropertyName("spore")]
    SPORE,
    [JsonPropertyName("petal")]
    PETAL,
    [JsonPropertyName("scrap")]
    SCRAP,
    [JsonPropertyName("beachside")]
    BEACHSIDE,
    [JsonPropertyName("pigman")]
    PIGMAN,
    [JsonPropertyName("toxic")]
    TOXIC,
    [JsonPropertyName("regal")]
    REGAL,
    [JsonPropertyName("vexing")]
    VEXING,
    [JsonPropertyName("voidglass")]
    VOIDGLASS,
    [JsonPropertyName("cosmicFoundations")]
    COSMIC_FOUNDATIONS,
    [JsonPropertyName("snail")]
    SNAIL,
    [JsonPropertyName("thanosLegionnaire")]
    THANOS_LEGIONNAIRE,
    [JsonPropertyName("uth")]
    UTH,
    [JsonPropertyName("cosmic")]
    COSMIC,
    [JsonPropertyName("leaf")]
    LEAF,
    [JsonPropertyName("tribal")]
    TRIBAL,
    [JsonPropertyName("saint's")]
    SAINTS,
    [JsonPropertyName("visceral")]
    VISCERAL,
    [JsonPropertyName("ascension")]
    ASCENSION,
    [JsonPropertyName("ultramarine")]
    ULTRAMARINE,
    [JsonPropertyName("taigaElk")]
    TAIGA_ELK,
    [JsonPropertyName("clock")]
    CLOCK,
    [JsonPropertyName("nii")]
    NII,
    [JsonPropertyName("moirai")]
    MOIRAI,
    [JsonPropertyName("bleeding")]
    BLEEDING,
    [JsonPropertyName("liffmail")]
    LIFFMAIL,
    [JsonPropertyName("elf")]
    ELF,
    [JsonPropertyName("slime")]
    SLIME,
    [JsonPropertyName("goblin")]
    GOBLIN,
    [JsonPropertyName("ghostly")]
    GHOSTLY,
    [JsonPropertyName("horse")]
    HORSE,
    [JsonPropertyName("snow")]
    SNOW,
    [JsonPropertyName("skien's")]
    SKIENS,
    [JsonPropertyName("thunderRelic")]
    THUNDER_RELIC,
    [JsonPropertyName("morph")]
    MORPH,
    [JsonPropertyName("black")]
    BLACK,
    [JsonPropertyName("earthRelic")]
    EARTH_RELIC,
    [JsonPropertyName("waterRelic")]
    WATER_RELIC,
    [JsonPropertyName("relic")]
    RELIC,
    [JsonPropertyName("outlaw")]
    OUTLAW,
    [JsonPropertyName("silverfish")]
    SILVERFISH,
    [JsonPropertyName("nether")]
    NETHER,
    [JsonPropertyName("fireRelic")]
    FIRE_RELIC,
    [JsonPropertyName("airRelic")]
    AIR_RELIC,
    [JsonPropertyName("adventurer")]
    ADVENTURER,
    [JsonPropertyName("darkened")]
    DARKENED,
    [JsonPropertyName("bovine")]
    BOVINE,
    [JsonPropertyName("bear")]
    BEAR,
    [JsonPropertyName("kaerynn")]
    KAERYNN,
    [JsonPropertyName("villager")]
    VILLAGER,
    [JsonPropertyName("spider")]
    SPIDER,
    [JsonPropertyName("conqueredSkies")]
    CONQUERED_SKIES,
    [JsonPropertyName("synchCore")]
    SYNCH_CORE,
    [JsonPropertyName("flashfire")]
    FLASHFIRE,
    [JsonPropertyName("jester")]
    JESTER,
    [JsonPropertyName("forgottenChronicles")]
    FORGOTTEN_CHRONICLES,
    [JsonPropertyName("wynnterfest2016")]
    WYNTERFEST2016,
    [JsonPropertyName("bandit's")]
    BANDITS,
    [JsonPropertyName("desert")]
    DESERT,
    [JsonPropertyName("blackCatalyst")]
    BLACK_CATALYST,
    [JsonPropertyName("constellation")]
    CONSTELLATION,
    [JsonPropertyName("hallowynn2016")]
    HALLOWYNN2016
}
