using System.Text.Json.Serialization;

namespace Tavstal.WynnNetSDK.Models.Items.Enums;

public enum EItemSubType
{
    [JsonPropertyName("bow")]
    BOW,
    [JsonPropertyName("dagger")]
    DAGGER,
    [JsonPropertyName("relik")]
    RELIK,
    [JsonPropertyName("spear")]
    SPEAR,
    [JsonPropertyName("wand")]
    WAND,
    [JsonPropertyName("boots")]
    BOOTS,
    [JsonPropertyName("chestplate")]
    CHESTPLATE,
    [JsonPropertyName("helmet")]
    HELMET,
    [JsonPropertyName("leggings")]
    LEGGINGS,
    [JsonPropertyName("bracelet")]
    BRACELET,
    [JsonPropertyName("necklace")]
    NECKLACE,
    [JsonPropertyName("ring")]
    RING,
    [JsonPropertyName("guildTome")]
    GUILD_TOME,
    [JsonPropertyName("armourTome")]
    ARMOUR_TOME,
    [JsonPropertyName("expertiseTome")]
    EXPERTISE_TOME,
    [JsonPropertyName("marathonTome")]
    MARATHON_TOME,
    [JsonPropertyName("mysticismTome")]
    MYSTICISM_TOME,
    [JsonPropertyName("lootrunTome")]
    LOOTRUN_TOME,
    [JsonPropertyName("weaponTome")]
    WEAPON_TOME,
    [JsonPropertyName("axe")]
    AXE,
    [JsonPropertyName("rod")]
    ROD,
    [JsonPropertyName("pickaxe")]
    PICKAXE,
    [JsonPropertyName("scythe")]
    SCYTHE,
    [JsonPropertyName("farming")]
    FARMING,
    [JsonPropertyName("fishing")]
    FISHING,
    [JsonPropertyName("mining")]
    MINING,
    [JsonPropertyName("woodcutting")]
    WOODCUTTING
}
