using System.Text.Json.Serialization;

namespace Tavstal.WynnNetSDK.Models.Items.Enums;

public enum EMajorId
{
    [JsonPropertyName("evershot")]
    EVERSHOT,
    [JsonPropertyName("forestSBlessing")]
    FOREST_S_BLESSING,
    [JsonPropertyName("fallout")]
    FALLOUT,
    [JsonPropertyName("twistingThreads")]
    TWISTING_THREADS,
    [JsonPropertyName("pioneerSEcho")]
    PIONEER_S_ECHO,
    [JsonPropertyName("altruism")]
    ALTRUISM,
    [JsonPropertyName("freerunner")]
    FREERUNNER,
    [JsonPropertyName("vedette")]
    VEDETTE,
    [JsonPropertyName("realityRevision")]
    REALITY_REVISION,
    [JsonPropertyName("seekingModule")]
    SEEKING_MODULE,
    [JsonPropertyName("fission")]
    FISSION,
    [JsonPropertyName("freneticSpirit")]
    FRENETIC_SPIRIT,
    [JsonPropertyName("netShot")]
    NET_SHOT,
    [JsonPropertyName("deathSentence")]
    DEATH_SENTENCE,
    [JsonPropertyName("regicide")]
    REGICIDE,
    [JsonPropertyName("selfSufficient")]
    SELF_SUFFICIENT,
    [JsonPropertyName("napalm")]
    NAPALM,
    [JsonPropertyName("riverofSouls")]
    RIVER_OF_SOULS,
    [JsonPropertyName("comboStomp")]
    COMBO_STOMP,
    [JsonPropertyName("gunkShot")]
    GUNK_SHOT,
    [JsonPropertyName("heartbeat")]
    HEARTBEAT,
    [JsonPropertyName("methodical")]
    METHODICAL,
    [JsonPropertyName("fantheHammer")]
    FAN_THE_HAMMER,
    [JsonPropertyName("wormhole")]
    WORMHOLE,
    [JsonPropertyName("punishment")]
    PUNISHMENT,
    [JsonPropertyName("grandInfluence")]
    GRAND_INFLUENCE,
    [JsonPropertyName("cherryBombs")]
    CHERRY_BOMBS,
    [JsonPropertyName("greed")]
    GREED,
    [JsonPropertyName("windsurf")]
    WINDSURF,
    [JsonPropertyName("hurricaneSEye")]
    HURRICANE_S_EYE,
    [JsonPropertyName("sorcery")]
    SORCERY,
    [JsonPropertyName("rovingAssassin")]
    ROVING_ASSASSIN,
    [JsonPropertyName("transcendence")]
    TRANSCENDENCE,
    [JsonPropertyName("efflorescence")]
    EFFLORESCENCE,
    [JsonPropertyName("spaceGlide")]
    SPACE_GLIDE,
    [JsonPropertyName("heatShimmer")]
    HEAT_SHIMMER,
    [JsonPropertyName("soulEater")]
    SOUL_EATER,
    [JsonPropertyName("juggle")]
    JUGGLE,
    [JsonPropertyName("flurryofBlows")]
    FLURRY_OF_BLOWS,
    [JsonPropertyName("incisionElegy")]
    INCISION_ELEGY,
    [JsonPropertyName("lightningCrash")]
    LIGHTNING_CRASH,
    [JsonPropertyName("livingMuseum")]
    LIVING_MUSEUM,
    [JsonPropertyName("manicEdge")]
    MANIC_EDGE,
    [JsonPropertyName("enlightenment")]
    ENLIGHTENMENT,
    [JsonPropertyName("ignitionWhirlwind")]
    IGNITION_WHIRLWIND,
    [JsonPropertyName("lifestream")]
    LIFESTREAM,
    [JsonPropertyName("peacefulEffigy")]
    PEACEFUL_EFFIGY,
    [JsonPropertyName("stringsofFate")]
    STRINGS_OF_FATE,
    [JsonPropertyName("ergosphere")]
    ERGOSPHERE,
    [JsonPropertyName("deadWeight")]
    DEAD_WEIGHTS,
    [JsonPropertyName("sublimation")]
    SUBLIMATION,
    [JsonPropertyName("furiousEffigy")]
    FURIOUS_EFFIGY,
    [JsonPropertyName("faustianGambit")]
    FAUSTIAN_GAMBIT,
    [JsonPropertyName("totemicFuse")]
    TOTEMIC_FUSE,
    [JsonPropertyName("geocentrism")]
    GEOCENTRISM,
    [JsonPropertyName("gruesomeKnots")]
    GRUESOME_KNOTS,
    [JsonPropertyName("starcrossed")]
    STARCROSSED,
    [JsonPropertyName("chaosReach")]
    CHAOS_REACH,
    [JsonPropertyName("flainRemnants")]
    FLAIN_REMNANTS,
    [JsonPropertyName("litFuse")]
    LIT_FUSE,
    [JsonPropertyName("rally")]
    RALLY,
    [JsonPropertyName("hellfire")]
    HELLFIRE,
    [JsonPropertyName("paragon")]
    PARAGON,
    [JsonPropertyName("divineHonor")]
    DIVINE_HONOR,
    [JsonPropertyName("trollBarge")]
    TROLL_BARGE,
    [JsonPropertyName("tidalDrift")]
    TIDAL_DRIFT,
    [JsonPropertyName("guardian")]
    GUARDIAN,
    [JsonPropertyName("lastResort")]
    LAST_RESORT,
    [JsonPropertyName("saviourSSacrifice")]
    SAVIOUR_S_SACRIFICE,
    [JsonPropertyName("scarceComfort")]
    SCARCE_COMFORT,
    [JsonPropertyName("vitriol")]
    VITRIOL,
    [JsonPropertyName("tackle")]
    TACKLE,
    [JsonPropertyName("divineRight")]
    DIVINE_RIGHT,
    [JsonPropertyName("slowBoil")]
    SLOW_BOIL,
    [JsonPropertyName("stagnantAir")]
    STAGNANT_AIR,
    [JsonPropertyName("oldSpark")]
    OLD_SPARK,
    [JsonPropertyName("oneselfUntoAll")]
    ONESELF_UNTO_ALL,
    [JsonPropertyName("temblor")]
    TEMBLOR,
    [JsonPropertyName("overwhelm")]
    OVERWHELM,
    [JsonPropertyName("meteorCrash")]
    METEOR_CRASH,
    [JsonPropertyName("earthenSplinter")]
    EARTHEN_SPLINTER,
    [JsonPropertyName("entropy")]
    ENTROPY,
    [JsonPropertyName("fixate")]
    FIXATE,
    [JsonPropertyName("lustrate")]
    LUSTRATE,
    [JsonPropertyName("inversion")]
    INVERSION,
    [JsonPropertyName("cosmicCapture")]
    COSMIC_CAPTURE,
    [JsonPropertyName("orbitalChain")]
    ORBITAL_CHAIN,
    [JsonPropertyName("perfectRecall")]
    PERFECT_RECALL,
    [JsonPropertyName("gravityWell")]
    GRAVITY_WELL,
    [JsonPropertyName("displace")]
    DISPLACE,
    [JsonPropertyName("lockdown")]
    LOCKDOWN,
    [JsonPropertyName("plague")]
    PLAGUE,
    [JsonPropertyName("solarWind")]
    SOLAR_WIND,
    [JsonPropertyName("wavebreak")]
    WAVEBREAK,
    [JsonPropertyName("gentleGlow")]
    GENTLE_GLOW,
    [JsonPropertyName("blindingLights")]
    BLINDING_LIGHTS,
    [JsonPropertyName("oneiro")]
    ONEIRO,
    [JsonPropertyName("dauntlessInferno")]
    DAUNTLESS_INFERNO,
    [JsonPropertyName("fissure")]
    FISSURE,
    [JsonPropertyName("flashfreeze")]
    FLASHFREEZE,
    [JsonPropertyName("perilousFlare")]
    PERILOUS_FLARE,
    [JsonPropertyName("explosiveImpact")]
    EXPLOSIVE_IMPACT,
    [JsonPropertyName("escapeRoute")]
    ESCAPE_ROUTE,
    [JsonPropertyName("lightweight")]
    LIGHTWEIGHT,
    [JsonPropertyName("pirouette")]
    PIROUETTE,
    [JsonPropertyName("lunge")]
    LUNGE,
    [JsonPropertyName("taunt")]
    TAUNT,
    [JsonPropertyName("desperateMeasures")]
    DESPERATE_MEASURES,
    [JsonPropertyName("rockShield")]
    ROCK_SHIELD,
    [JsonPropertyName("cannulate")]
    CANNULATE,
    [JsonPropertyName("snowySteps")]
    SNOWY_STEPS,
    [JsonPropertyName("phoenixBorn")]
    PHOENIX_BORN,
    [JsonPropertyName("superconductor")]
    SUPERCONDUCTOR,
    [JsonPropertyName("magnet")]
    MAGNET,
    [JsonPropertyName("alterEgo")]
    ALTER_EGO,
    [JsonPropertyName("mangle")]
    MANGLE,
    [JsonPropertyName("intangible")]
    INTANGIBLE,
    [JsonPropertyName("iceStorm")]
    ICE_STORM,
    [JsonPropertyName("pounce")]
    POUNCE,
    [JsonPropertyName("hawkeye")]
    HAWKEYE,
    [JsonPropertyName("orbwalk")]
    ORBWALK,
    [JsonPropertyName("burntShadows")]
    BURNT_SHADOWS,
    [JsonPropertyName("frightorFlight")]
    FRIGHT_OR_FLIGHT,
    [JsonPropertyName("festiveSpirit")]
    FESTIVE_SPIRIT,
    [JsonPropertyName("sunEater")]
    SUN_EATER,
    [JsonPropertyName("recklessAbandon")]
    RECKLESS_ABANDON,
    [JsonPropertyName("expunge")]
    EXPUNGE,
    [JsonPropertyName("brachiate")]
    BRACHIATE,
    [JsonPropertyName("rustedIchor")]
    RUSTED_ICHOR,
    [JsonPropertyName("findThyself")]
    FIND_THYSELF,
    [JsonPropertyName("madness")]
    MADNESS,
    [JsonPropertyName("clamber")]
    CLAMBER,
    [JsonPropertyName("splitSecond")]
    SPLIT_SECOND,
    [JsonPropertyName("spectralMemory")]
    SPECTRAL_MEMORY,
    [JsonPropertyName("insoluble")]
    INSOLUBLE,
    [JsonPropertyName("boundbyBlood")]
    BOUND_BY_BLOOD,
    [JsonPropertyName("mobMentality")]
    MOB_MENTALITY,
    [JsonPropertyName("lasso")]
    LASSO,
    [JsonPropertyName("coagulate")]
    COAGULATE,
    [JsonPropertyName("flightBurst")]
    FLIGHT_BURST,
    [JsonPropertyName("culicidaeCreed")]
    CULICIDAE_CREED,
    [JsonPropertyName("powerFist")]
    POWER_FIST,
    [JsonPropertyName("brutalBlow")]
    BRUTAL_BLOW
}
